from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('detail', views.detail, name = 'detail'),
    path('category', views.category, name = 'category'),
    path('register', views.register, name = 'register'),
    path('login', views.login, name = 'login'),
    path('logout', views.logout, name = 'logout'),
    path('account', views.account, name = 'account'),
    path('product', views.product, name = 'product'),
    path('addProduct', views.addProduct, name = 'addProduct'),
    path('deleteProduct', views.deleteProduct, name = 'deleteProduct'),
    path('editProduct', views.editProduct, name = 'editProduct'),
    path('cart', views.cart, name = 'cart'),
    path('chooseSize', views.chooseSize, name = 'chooseSize'),
    path('addToCart', views.addToCart, name = 'addToCart'),
    path('profile', views.profile, name = 'profile'),
    path('deleteFromCart', views.deleteFromCart, name = 'deleteFromCart'),
    path('yourOrder', views.yourOrder, name = 'yourOrder'),
    path('cancelOrder', views.cancelOrder, name = 'cancelOrder'),
    path('completeOrder', views.completeOrder, name = 'completeOrder'),
    path('customerOrder', views.customerOrder, name = 'customerOrder'),
    path('registerSeller', views.registerSeller, name = 'registerSeller'),
    path('myshop', views.myshop, name = 'myshop'),
    path('categoryShop', views.categoryShop, name = 'categoryShop'),
    path('detailShop', views.detailShop, name = 'detailShop'),
    path('deleteAccount', views.deleteAccount, name = 'deleteAccount'),
    path('registerAdmin', views.registerAdmin, name = 'registerAdmin'),
    path('search', views.search, name = 'search'),
    path('searchShop', views.searchShop, name = 'searchShop'),
    path('increase', views.increase, name = 'increase'),
    path('decrease', views.decrease, name = 'decrease'),
]