# Generated by Django 4.2.5 on 2023-09-23 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
