# Generated by Django 4.2.5 on 2023-09-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
