# Generated by Django 4.2.5 on 2023-09-28 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.account'),
        ),
    ]
