# Generated by Django 4.2.5 on 2023-09-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_category_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='account',
        ),
    ]
