# Generated by Django 4.2.5 on 2023-10-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_product_size_productsize_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
