# Generated by Django 4.2.5 on 2023-10-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
