# Generated by Django 4.2.5 on 2023-10-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.IntegerField(null=True),
        ),
    ]
